apiVersion: v2
name: dagster
description: A Helm chart for Kubernetes
type: application
dependencies:
  - name: dagster
    repository: https://dagster-io.github.io/helm
    version: 1.11.10
  # - name: kubernetes-dashboard
  #   repository: https://kubernetes.github.io/dashboard/
  #   version: 7.13.0

version: 0.1.0

appVersion: "1.16.0"
